-- MySQL Script generated by MySQL Workbench
-- 08/02/14 11:11:48
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Aplicacion_Base
-- -----------------------------------------------------
-- 		
CREATE SCHEMA IF NOT EXISTS `Aplicacion_Base` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Aplicacion_Base` ;

-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Catedratico` (
  `idCatedratico` INT NOT NULL,
  `Primer_Nombre` VARCHAR(20) NOT NULL,
  `Segundo_Nombre` VARCHAR(20) NOT NULL,
  `Primer_Apellido` VARCHAR(20) NOT NULL,
  `Segundo_Apellido` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCatedratico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Nivel_Educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Nivel_Educativo` (
  `idNivel_Educativo` INT NOT NULL,
  `Descripcion` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idNivel_Educativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Grado` (
  `idGrado` INT NOT NULL,
  `Nombre_Grado` VARCHAR(25) NOT NULL,
  `Catedratico_idCatedratico` INT NOT NULL,
  `Nivel_Educativo_idNivel_Educativo` INT NOT NULL,
  PRIMARY KEY (`idGrado`, `Catedratico_idCatedratico`, `Nivel_Educativo_idNivel_Educativo`),
  INDEX `fk_Grado_Catedratico1_idx` (`Catedratico_idCatedratico` ASC),
  INDEX `fk_Grado_Nivel_Educativo1_idx` (`Nivel_Educativo_idNivel_Educativo` ASC),
  CONSTRAINT `fk_Grado_Catedratico1`
    FOREIGN KEY (`Catedratico_idCatedratico`)
    REFERENCES `Aplicacion_Base`.`Catedratico` (`idCatedratico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grado_Nivel_Educativo1`
    FOREIGN KEY (`Nivel_Educativo_idNivel_Educativo`)
    REFERENCES `Aplicacion_Base`.`Nivel_Educativo` (`idNivel_Educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Tipo_Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Tipo_Matricula` (
  `idTipo_Matricula` INT NOT NULL,
  `Desripcion` VARCHAR(25) NULL,
  PRIMARY KEY (`idTipo_Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Sexo` (
  `idSexo` INT NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `Primer_Nombre` VARCHAR(45) NOT NULL,
  `Segundo_Nombre` VARCHAR(45) NOT NULL,
  `Primer_Apellido` VARCHAR(45) NOT NULL,
  `Segundo_Apellido` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Tipo_Matricula_idTipo_Matricula` INT NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`, `Departamento_idDepartamento`, `Tipo_Matricula_idTipo_Matricula`, `Sexo_idSexo`),
  INDEX `fk_Matricula_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  INDEX `fk_Matricula_Tipo_Matricula1_idx` (`Tipo_Matricula_idTipo_Matricula` ASC),
  INDEX `fk_Matricula_Sexo1_idx` (`Sexo_idSexo` ASC),
  CONSTRAINT `fk_Matricula_Departamento`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `Aplicacion_Base`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Tipo_Matricula`
    FOREIGN KEY (`Tipo_Matricula_idTipo_Matricula`)
    REFERENCES `Aplicacion_Base`.`Tipo_Matricula` (`idTipo_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `Aplicacion_Base`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aplicacion_Base`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion_Base`.`Matricula` (
  `idMatricula` INT NOT NULL,
  `Fecha` DATE NULL,
  `Grado_idGrado` INT NOT NULL,
  `Grado_Catedratico_idCatedratico` INT NOT NULL,
  `Grado_Nivel_Educativo_idNivel_Educativo` INT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  `Estudiante_Departamento_idDepartamento` INT NOT NULL,
  `Estudiante_Tipo_Matricula_idTipo_Matricula` INT NOT NULL,
  `Estudiante_Sexo_idSexo` INT NOT NULL,
  PRIMARY KEY (`idMatricula`, `Grado_idGrado`, `Grado_Catedratico_idCatedratico`, `Grado_Nivel_Educativo_idNivel_Educativo`, `Estudiante_idEstudiante`, `Estudiante_Departamento_idDepartamento`, `Estudiante_Tipo_Matricula_idTipo_Matricula`, `Estudiante_Sexo_idSexo`),
  INDEX `fk_Inscripcion_Grado1_idx` (`Grado_idGrado` ASC, `Grado_Catedratico_idCatedratico` ASC, `Grado_Nivel_Educativo_idNivel_Educativo` ASC),
  INDEX `fk_Matricula_Estudiante1_idx` (`Estudiante_idEstudiante` ASC, `Estudiante_Departamento_idDepartamento` ASC, `Estudiante_Tipo_Matricula_idTipo_Matricula` ASC, `Estudiante_Sexo_idSexo` ASC),
  CONSTRAINT `fk_Inscripcion_Grado`
    FOREIGN KEY (`Grado_idGrado` , `Grado_Catedratico_idCatedratico` , `Grado_Nivel_Educativo_idNivel_Educativo`)
    REFERENCES `Aplicacion_Base`.`Grado` (`idGrado` , `Catedratico_idCatedratico` , `Nivel_Educativo_idNivel_Educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Estudiante`
    FOREIGN KEY (`Estudiante_idEstudiante` , `Estudiante_Departamento_idDepartamento` , `Estudiante_Tipo_Matricula_idTipo_Matricula` , `Estudiante_Sexo_idSexo`)
    REFERENCES `Aplicacion_Base`.`Estudiante` (`idEstudiante` , `Departamento_idDepartamento` , `Tipo_Matricula_idTipo_Matricula` , `Sexo_idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
